import * as THREE from './vendor/three.module.js';
// A bounded dust pool: faint persistent air and motion-driven lift from the book's perimeter.
export function setupAtmosphere(){
 const stage=document.querySelector('.stage'),host=document.querySelector('.ambient'),book=document.querySelector('#book'),button=document.querySelector('#effects-settings'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
 let off=false;try{off=localStorage.getItem('felt-reader-effects-v1')==='off';}catch{}
 let renderer,deskRenderer,deskScene,scene,camera,raf=0,last=0,title='',rect,turning=false,previous=0,budget=0,serial=0;
 const DESK=1000,AIR=1500,MAX=8000,pool=Array.from({length:MAX},(_,i)=>({phase:i*.87,seed:((i*37+13)%101)/101,life:0})),position=new Float32Array(MAX*3),colour=new Float32Array(MAX*3),alpha=new Float32Array(MAX),size=new Float32Array(MAX);
 try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.setAttribute('aria-hidden','true');document.body.append(host);host.replaceChildren(renderer.domElement);scene=new THREE.Scene();}catch{button.disabled=true;button.textContent='Effects unavailable';return {scene(){}};}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(position,3));geometry.setAttribute('dustColour',new THREE.BufferAttribute(colour,3));geometry.setAttribute('dustAlpha',new THREE.BufferAttribute(alpha,1));geometry.setAttribute('dustSize',new THREE.BufferAttribute(size,1));
 const material=new THREE.ShaderMaterial({transparent:true,depthTest:false,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{pixelRatio:{value:renderer.getPixelRatio()}},vertexShader:`attribute vec3 dustColour;attribute float dustAlpha;attribute float dustSize;varying vec3 tint;varying float opacity;uniform float pixelRatio;void main(){tint=dustColour;opacity=dustAlpha;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);gl_PointSize=dustSize*pixelRatio;}`,fragmentShader:`varying vec3 tint;varying float opacity;void main(){vec2 p=gl_PointCoord*2.0-1.0;float r=length(p);float halo=exp(-r*r*6.0);float core=exp(-r*r*35.0);float glint=pow(max(0.0,1.0-abs(p.x)),22.0)*pow(max(0.0,1.0-abs(p.y)),3.0)+pow(max(0.0,1.0-abs(p.y)),22.0)*pow(max(0.0,1.0-abs(p.x)),3.0);gl_FragColor=vec4(mix(tint,vec3(1.0),core*.65),opacity*(halo*.38+core*.75+glint*.65));}`});
 const deskHost=document.createElement('div');deskHost.className='desk-dust';deskHost.setAttribute('aria-hidden','true');document.body.prepend(deskHost);deskRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});deskRenderer.setPixelRatio(renderer.getPixelRatio());deskHost.append(deskRenderer.domElement);deskScene=new THREE.Scene();const deskGeometry=new THREE.BufferGeometry();for(const [name,attr] of Object.entries(geometry.attributes))deskGeometry.setAttribute(name,attr);deskGeometry.setDrawRange(0,DESK);const deskPoints=new THREE.Points(deskGeometry,material);deskPoints.frustumCulled=false;deskScene.add(deskPoints);geometry.setDrawRange(DESK,MAX-DESK);
 const points=new THREE.Points(geometry,material);points.frustumCulled=false;scene.add(points);const c=new THREE.Color(),gold=new THREE.Color('#e8c67f'),silver=new THREE.Color('#e5e7ec'),opalBlue=new THREE.Color('#cce9ef'),opalPink=new THREE.Color('#e7d7ed');host.dataset.dustPalette='gold-silver-opal-glints';host.dataset.dustForeground='500';host.dataset.dustCoverage='surface-and-perimeter';
 function bounds(){const b=book.getBoundingClientRect(),s={left:0,top:0};rect={left:b.left-s.left,right:b.right-s.left,top:b.top-s.top,bottom:b.bottom-s.top,width:b.width,height:b.height};}
 function rebuild(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);deskRenderer.setSize(w,h);camera=new THREE.OrthographicCamera(0,w,0,h,-10,10);camera.position.z=5;bounds();pool.slice(0,AIR).forEach((p,i)=>{p.x=8+p.seed*(w-16);p.y=8+((i*61+7)%103)/103*(h-16);p.baseX=p.x;p.baseY=p.y;});}
 function allowed(){return !off&&!reduced.matches&&!document.hidden;}
 function emit(count,progress,direction,speed){bounds();for(let k=0;k<count;k++){const i=AIR+(serial++%(MAX-AIR)),p=pool[i],f=Math.random();const edge=Math.floor(serial/2)%4,theta=Math.random()*Math.PI*2;let nx=0,ny=0;
 if(k%2===0){p.x=rect.left+Math.random()*rect.width;p.y=rect.top+Math.random()*rect.height;const cx=rect.left+rect.width/2,cy=rect.top+rect.height/2;const distance=Math.hypot(p.x-cx,p.y-cy)||1;nx=(p.x-cx)/distance;ny=(p.y-cy)/distance;}
 else if(edge===0){p.x=rect.left+f*rect.width;p.y=rect.top-2;ny=-1;}
 else if(edge===1){p.x=rect.right+2;p.y=rect.top+f*rect.height;nx=1;}
 else if(edge===2){p.x=rect.left+f*rect.width;p.y=rect.bottom+2;ny=1;}
 else{p.x=rect.left-2;p.y=rect.top+f*rect.height;nx=-1;}
 host.dataset.dustSurfaceEmissions=String(Number(host.dataset.dustSurfaceEmissions||0)+(k%2===0?1:0));p.x+=(Math.random()-.5)*8;p.y+=(Math.random()-.5)*8;const velocity=25+Math.random()*145+speed*65;p.vx=nx*velocity+Math.cos(theta)*45;p.vy=ny*velocity+Math.sin(theta)*45;
 host.dataset.dustEdges='top,right,bottom,left';p.life=2.1+f*1.5;p.total=p.life;p.born=performance.now()*.001;p.x0=p.x;p.y0=p.y;}host.dataset.dustEmissions=String(serial);}
 window.addEventListener('felt-turn',e=>{if(!allowed())return;const {progress:p,direction,start}=e.detail;if(start){turning=true;previous=p;budget=0;host.dataset.dustTurns=String(Number(host.dataset.dustTurns||0)+1);emit(1840,p,direction,.3);}const delta=Math.abs(p-previous);previous=p;budget+=delta*4140;const n=Math.min(240,Math.floor(budget));if(n){budget-=n;emit(n,p,direction,Math.min(1,delta*30));}});
 window.addEventListener('felt-turn-end',()=>{turning=false;});
 function draw(time,dt){bounds();const t=time*.001;let active=0,overBook=0;for(let i=0;i<MAX;i++){const p=pool[i];if(i<AIR){p.x=p.baseX+Math.sin(t*.22+p.phase)*9;p.y=p.baseY+Math.cos(t*.17+p.phase)*11;const flash=Math.pow(Math.max(0,Math.sin(t*(1.2+p.seed*1.9)+p.phase)),14);alpha[i]=.24+flash*.65;size[i]=i%19===0?4.5+flash*3:1.3+(i%5)*.28;if(i>=DESK){alpha[i]*=1.35;size[i]*=1.25;}if(turning){p.x+=Math.sin(t*2+p.phase)*2;p.y-=2;}}else{p.life=Math.max(0,p.life-dt);if(p.life>0){active++;const ageFlow=1-p.life/p.total;const cx=(rect.left+rect.right)/2,cy=(rect.top+rect.bottom)/2;p.vx+=((cx-p.x)*.22*ageFlow+Math.sin(t*1.7+p.phase)*32)*dt;p.vy+=((cy-p.y)*.22*ageFlow+Math.cos(t*1.3+p.phase)*28+6)*dt;p.vx*=Math.exp(-.65*dt);p.x+=p.vx*dt+Math.sin(t*2+p.phase)*dt*8;p.y+=p.vy*dt;const age=1-p.life/p.total;const twinkle=.55+.65*Math.pow(Math.max(0,Math.sin(t*(3+p.seed*4)+p.phase)),8);alpha[i]=twinkle*Math.min(1,age*12)*Math.pow(1-age,1.1);size[i]=i%61===0?10+(1-age)*5:i%23===0?6+(1-age)*3:1.6+(i%8)*.28;}else{alpha[i]=0;p.x=p.y=-100;}}
 if(i>=DESK&&i<AIR&&alpha[i]>0&&p.x>rect.left&&p.x<rect.right&&p.y>rect.top&&p.y<rect.bottom)overBook++;
 // Predominantly gold/silver; rare turning glints carry a restrained opal tint.
 c.copy(i%3===0?gold:silver);if(i>=AIR&&i%61===0)c.lerp(i%2?opalBlue:opalPink,.35);c.multiplyScalar(.85+.15*Math.sin(t*.6+p.phase)**2);position[i*3]=p.x;position[i*3+1]=p.y;position[i*3+2]=0;colour[i*3]=c.r;colour[i*3+1]=c.g;colour[i*3+2]=c.b;}
 for(const a of Object.values(geometry.attributes))a.needsUpdate=true;host.dataset.dustOverBook=String(overBook);host.dataset.dustActive=String(active);host.dataset.dustAmbient=String(AIR);deskRenderer.render(deskScene,camera);renderer.render(scene,camera);}
 function loop(time){raf=0;if(!allowed())return;if(time-last>=30){const dt=Math.min(.05,Math.max(0,(time-last)*.001));last=time;draw(time,dt);}raf=requestAnimationFrame(loop);}
 function state(){const on=!off&&!reduced.matches;button.textContent=on?'Effects on':'Effects off';button.setAttribute('aria-pressed',String(on));button.disabled=reduced.matches;stage.classList.toggle('effects-off',!on);host.hidden=!on;deskHost.hidden=!on;cancelAnimationFrame(raf);raf=0;host.dataset.magicVisible=String(on&&!document.hidden);if(!allowed()){pool.slice(AIR).forEach(p=>p.life=0);host.dataset.dustActive='0';turning=false;return;}rebuild();last=performance.now();draw(last,0);raf=requestAnimationFrame(loop);}
 button.onclick=()=>{off=!off;try{localStorage.setItem('felt-reader-effects-v1',off?'off':'on');}catch{}state();};reduced.addEventListener('change',state);document.addEventListener('visibilitychange',state);new ResizeObserver(rebuild).observe(stage);window.addEventListener('resize',rebuild);state();return {scene(next){if(title!==next){title=next;rebuild();}stage.dataset.atmosphere='iridescent-dust';}};
}

