import * as THREE from './vendor/three.module.js';
const fallback=window.FeltPaperTurn,book=document.querySelector('#book'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
let renderer,contextLost=false;
try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();contextLost=true;});renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;});}catch{document.documentElement.dataset.pageRenderer='css-fallback';}
const pageSnapshots=new Map();
function snapshotKey(page,w,h){return w+'|'+h+'|'+page.innerHTML;}
async function prepare(options){const {host,front,back}=options;await Promise.all([front,back].flatMap(page=>[...page.querySelectorAll('img')].map(img=>img.decode())));const w=host.clientWidth/2,h=host.clientHeight;const measure=document.createElement('div');measure.className='spread';measure.style.cssText='position:absolute;inset:0;visibility:hidden;pointer-events:none';measure.append(front,back);host.append(measure);const transform=host.style.transform;const jobs=[];try{host.style.transform='none';for(const page of [front,back]){page.style.width=w+'px';page.style.height=h+'px';const key=snapshotKey(page,w,h);if(pageSnapshots.has(key))continue;const clone=page.cloneNode(true),sources=[page,...page.querySelectorAll('*')],targets=[clone,...clone.querySelectorAll('*')];sources.forEach((source,i)=>{const style=getComputedStyle(source);targets[i].style.cssText=[...style].map(name=>name+':'+style.getPropertyValue(name)).join(';');targets[i].style.visibility='visible';for(const pseudo of ['::before','::after']){const ps=getComputedStyle(source,pseudo);if(ps.content==='none'||ps.content==='normal')continue;const decoration=document.createElement('span');decoration.style.cssText=[...ps].map(name=>name+':'+ps.getPropertyValue(name)).join(';');decoration.style.visibility='visible';pseudo==='::before'?targets[i].prepend(decoration):targets[i].append(decoration);}if(source.tagName==='IMG'){const raster=document.createElement('canvas');raster.width=source.naturalWidth;raster.height=source.naturalHeight;raster.getContext('2d').drawImage(source,0,0);targets[i].src=raster.toDataURL();}});clone.style.cssText+=';position:relative;left:0;top:0;width:'+w+'px;height:'+h+'px;visibility:visible';const markup=new XMLSerializer().serializeToString(clone),svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'"><foreignObject width="100%" height="100%">'+markup+'</foreignObject></svg>';jobs.push(new Promise((resolve,reject)=>{const image=new Image(),timer=setTimeout(()=>reject(Error('Page snapshot timed out')),3000);image.onload=()=>{clearTimeout(timer);try{const canvas=document.createElement('canvas');canvas.width=Math.round(w*2);canvas.height=Math.round(h*2);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);canvas.getContext('2d').getImageData(0,0,1,1);pageSnapshots.set(key,canvas);while(pageSnapshots.size>8)pageSnapshots.delete(pageSnapshots.keys().next().value);resolve();}catch(e){reject(e);}};image.onerror=()=>{clearTimeout(timer);reject(Error('Page snapshot unavailable'));};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);}));}}finally{host.style.transform=transform;measure.remove();}try{await Promise.all(jobs);document.documentElement.dataset.pageSnapshot='exact-dom';}catch(error){document.documentElement.dataset.pageSnapshot='raster-fallback';console.warn('Printed page snapshot fallback',error);}}
function texture(page,w,h){const exact=pageSnapshots.get(snapshotKey(page,w,h));if(exact){document.documentElement.dataset.printedSnapshot='exact-dom';const tex=new THREE.CanvasTexture(exact);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;}const canvas=document.createElement('canvas');canvas.width=Math.round(w*2);canvas.height=Math.round(h*2);const ctx=canvas.getContext('2d');ctx.scale(2,2);const img=page.querySelector('img');if(!img?.complete||!img.naturalWidth)throw Error('Illustration is still loading');if(img.classList.contains('tree-fill-image')){const sh=img.naturalHeight,sw=sh*1.5,sx=(img.naturalWidth-sw)/2+(img.classList.contains('right')?sw/2:0);ctx.drawImage(img,sx,0,sw/2,sh,0,0,w,h);}else if(getComputedStyle(img).objectFit==='contain'){const scale=Math.min(w/img.naturalWidth,h/img.naturalHeight),iw=img.naturalWidth*scale,ih=img.naturalHeight*scale;ctx.fillStyle='#17191c';ctx.fillRect(0,0,w,h);ctx.drawImage(img,(w-iw)/2,(h-ih)/2,iw,ih);}else ctx.drawImage(img,0,0,w,h);
 // Read the already-laid-out DOM caption, including its private edits. The canonical text remains in the DOM.
 const pageRect=page.getBoundingClientRect();for(const line of page.querySelectorAll('.tape-line')){const style=getComputedStyle(line),saved=line.style.transform;line.style.transform='none';const rect=line.getBoundingClientRect();line.style.transform=saved;const angle=parseFloat(style.getPropertyValue('--tilt'))*Math.PI/180||0,scale=rect.width/line.offsetWidth||1;ctx.save();ctx.translate(rect.left-pageRect.left+rect.width/2,rect.top-pageRect.top+rect.height/2);ctx.translate((parseFloat(style.getPropertyValue('--shift'))||0)*scale,0);ctx.rotate(angle);ctx.scale(scale,scale);const lw=line.offsetWidth,lh=line.offsetHeight;ctx.translate(-lw/2,-lh/2);ctx.beginPath();const poly=line.style.getPropertyValue('--tear').slice(8,-1).split(/,(?![^()]*\))/);function coord(v,total){v=v.trim();if(v.startsWith('calc'))return total-parseFloat(v.split('-')[1]);return v.endsWith('%')?parseFloat(v)*total/100:parseFloat(v);}poly.forEach((point,j)=>{const match=point.trim().match(/^(calc\([^)]*\)|[^ ]+)\s+(.+)$/);if(!match)return;const x=coord(match[1],lw),y=coord(match[2],lh);j?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.globalAlpha=parseFloat(getComputedStyle(line.closest('.story-copy')).getPropertyValue('--tape-opacity'))||.78;ctx.fillStyle=style.getPropertyValue('--paper')||'#eadbb7';ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=style.color;ctx.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(line.textContent,lw/2,lh/2);ctx.restore();}
 const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;}
function create(options){if(!renderer||contextLost||reduced.matches)return fallback.create(options);let frontTex,backTex,layer,turnScene;
try{const {host,direction,front,back,underlay,stationary}=options;const rect={width:host.clientWidth,height:host.clientHeight},w=rect.width/2,h=rect.height;
 // Measure caption clones in the actual book container so text wrapping and container units agree.
 const measure=document.createElement('div');measure.style.cssText=`position:absolute;inset:0;visibility:hidden;pointer-events:none`;front.style.width=back.style.width=w+'px';front.style.height=back.style.height=h+'px';measure.append(front,back);host.append(measure);const frozenTransform=host.style.transform;try{host.style.transform="none";frontTex=texture(front,w,h);backTex=texture(back,w,h);}finally{host.style.transform=frozenTransform;measure.remove();}
 layer=document.createElement('div');layer.className='paper-turn';layer.setAttribute('aria-hidden','true');underlay.classList.add('paper-underlay');stationary.className='stationary';stationary.style[direction===1?'left':'right']='0';const startPage=front.cloneNode(true);startPage.classList.add("turn-start-page");startPage.style.width="50%";startPage.style[direction===1?"right":"left"]="0";layer.append(underlay,stationary,startPage);const innerCrease=document.createElement('div');innerCrease.className='crease turn-crease';innerCrease.setAttribute('aria-hidden','true');layer.append(innerCrease);host.append(layer);
 const turnPad=96;renderer.setSize(rect.width+turnPad*2,h+turnPad*2);renderer.domElement.className='three-leaf';renderer.domElement.style.left=renderer.domElement.style.top=-turnPad+'px';layer.append(renderer.domElement);
 const scene=turnScene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,(rect.width+turnPad*2)/(h+turnPad*2),1,5000);camera.position.z=(h+turnPad*2)/(2*Math.tan(THREE.MathUtils.degToRad(17.5)));camera.lookAt(0,0,0);
 scene.add(new THREE.AmbientLight(0xffffff,1.7));const light=new THREE.DirectionalLight(0xffedcf,1.2);light.position.set(-w*.7,h*.8,1500);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-w*1.7,right:w*1.7,top:h,bottom:-h,near:1,far:3000});light.shadow.bias=-.00015;light.shadow.normalBias=2;light.shadow.radius=4;scene.add(light);const receiverGeometry=new THREE.PlaneGeometry(w*2,h);const receiverMaterial=new THREE.ShadowMaterial({opacity:.32});const receiver=new THREE.Mesh(receiverGeometry,receiverMaterial);receiver.position.z=-3;receiver.receiveShadow=true;scene.add(receiver);
 const geometry=new THREE.PlaneGeometry(w,h,64,20);if(direction===-1){const forwardUV=geometry.attributes.uv;for(let i=0;i<forwardUV.count;i++)forwardUV.setX(i,1-forwardUV.getX(i));}const reverse=geometry.clone();const uv=reverse.attributes.uv;for(let i=0;i<uv.count;i++)uv.setX(i,1-uv.getX(i));
 const mat=new THREE.MeshBasicMaterial({map:frontTex,side:THREE.FrontSide,toneMapped:false});const backMat=new THREE.MeshBasicMaterial({map:backTex,side:THREE.BackSide,toneMapped:false});const face=new THREE.Mesh(geometry,mat),rear=new THREE.Mesh(reverse,backMat);face.castShadow=true;rear.castShadow=false;scene.add(face,rear);const perimeter=[];for(let c=0;c<=64;c++)perimeter.push(c);for(let r=1;r<=20;r++)perimeter.push(r*65+64);for(let c=63;c>=0;c--)perimeter.push(20*65+c);for(let r=19;r>=1;r--)perimeter.push(r*65);perimeter.push(0);const rimGeometry=new THREE.BufferGeometry();rimGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(perimeter.length*6),3));const rimIndices=[];for(let j=0;j<perimeter.length-1;j++){const a=j*2;rimIndices.push(a,a+1,a+2,a+1,a+3,a+2);}rimGeometry.setIndex(rimIndices);const rimMaterial=new THREE.MeshStandardMaterial({color:0xe9d8b6,side:THREE.DoubleSide,roughness:1});const rim=new THREE.Mesh(rimGeometry,rimMaterial);rim.castShadow=true;scene.add(rim);
 const shadow=document.createElement('div');shadow.className='paper-shadow';layer.insertBefore(shadow,renderer.domElement);shadow.style.filter='blur(8px)';
 function progress(p,grab={}){if(contextLost)throw Error('Page graphics context lost');const curl=Math.sin(Math.PI*p);receiverMaterial.opacity=.16*Math.pow(curl,1.2);const positions=geometry.attributes.position,other=reverse.attributes.position;const steps=64,dx=w/steps;let tipX=0;
 for(let row=0;row<=20;row++){let x=0,z=0;const v=row/20,y=h/2-v*h;for(let column=0;column<=steps;column++){const u=column/steps,i=row*(steps+1)+column;const anchor=options.anchorY??.5,reach=Math.exp(-Math.abs(v-anchor)*3.5);const sag=curl*u*u*((grab.pullY??0)*h*.45*reach+(v-anchor)*h*.13+Math.sin(p*Math.PI*2.4+v*4)*h*.03);positions.setXYZ(i,direction*x,y+sag,z);other.setXYZ(i,direction*x,y+sag,z-.8);if(column<steps){const f=(column+.5)/steps;const anchor=options.anchorY??.5,proximity=Math.exp(-Math.abs(v-anchor)*3.5);const cornerLag=(v-anchor)*1.25*f+(grab.pullY??0)*1.5*proximity*f;const flutter=Math.sin(p*Math.PI*3.2+v*4.5)*.13*f*f;const angle=Math.PI*p+curl*(-1.05+2.05*Math.pow(f,1.35)+cornerLag+flutter);x+=dx*Math.cos(angle);z+=dx*Math.sin(angle);}if(row===10&&column===steps)tipX=x;}}
 geometry.computeVertexNormals();const normals=geometry.attributes.normal;for(let i=0;i<positions.count;i++)other.setXYZ(i,positions.getX(i)-direction*normals.getX(i)*.5,positions.getY(i)-direction*normals.getY(i)*.5,positions.getZ(i)-direction*normals.getZ(i)*.5);
 const rimPositions=rimGeometry.attributes.position;perimeter.forEach((point,j)=>{rimPositions.setXYZ(j*2,positions.getX(point),positions.getY(point),positions.getZ(point));rimPositions.setXYZ(j*2+1,other.getX(point),other.getY(point),other.getZ(point));});rimPositions.needsUpdate=true;rimGeometry.computeVertexNormals();
 mat.side=direction===1?THREE.FrontSide:THREE.BackSide;backMat.side=direction===1?THREE.BackSide:THREE.FrontSide;geometry.computeVertexNormals();reverse.computeVertexNormals();positions.needsUpdate=other.needsUpdate=true;const ease=x=>x*x*(3-2*x);const entry=ease(Math.min(1,p/.06)),exit=ease(Math.max(0,Math.min(1,(p-.94)/.06)));renderer.domElement.style.opacity='1';startPage.style.visibility='hidden';startPage.style.opacity='0';stationary.style.opacity='1';renderer.render(scene,camera);shadow.style.display='none';}

 progress(0);document.documentElement.dataset.pageRenderer='three';return {layer,leaf:renderer.domElement,stationary,progress,segments:64,remove(){layer.remove();geometry.dispose();reverse.dispose();rimGeometry.dispose();rimMaterial.dispose();receiverGeometry.dispose();receiverMaterial.dispose();mat.dispose();backMat.dispose();frontTex.dispose();backTex.dispose();}};
}catch(error){layer?.remove();const disposed=new Set();turnScene?.traverse(object=>{for(const resource of [object.geometry,...(Array.isArray(object.material)?object.material:[object.material])])if(resource&&!disposed.has(resource)){disposed.add(resource);resource.dispose();}});frontTex?.dispose();backTex?.dispose();console.warn('Using accessible CSS paper fallback',error);return fallback.create(options);}}
if(renderer){window.FeltPaperTurn={supported:fallback.supported,create,prepare};document.documentElement.dataset.pageRenderer='three-ready';}
// Persistent Three.js book body. The DOM is the accessible printed surface; WebGL supplies its physical binding and paper below.
let bodyRenderer;
try{bodyRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});bodyRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));bodyRenderer.shadowMap.enabled=true;bodyRenderer.shadowMap.type=THREE.PCFSoftShadowMap;bodyRenderer.domElement.className='three-book-body';bodyRenderer.domElement.setAttribute('aria-hidden','true');book.prepend(bodyRenderer.domElement);document.documentElement.classList.add('three-book-ready');}catch{ /* CSS binding remains available without WebGL. */ }
let bodyResources=[];
function drawBody(){if(!bodyRenderer)return;bodyResources.forEach(x=>x.dispose());bodyResources=[];const width=book.clientWidth,height=book.clientHeight,pad=48;bodyRenderer.setSize(width+pad*2,height+pad*2);const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-(width+pad*2)/2,(width+pad*2)/2,(height+pad*2)/2,-(height+pad*2)/2,1,4000);camera.position.set(0,0,2000);camera.lookAt(0,0,0);scene.add(new THREE.AmbientLight(0xf4f1e7,1.8));const light=new THREE.DirectionalLight(0xffe7c4,1.6);light.position.set(-width*.6,height*.8,1200);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-width,right:width,top:height,bottom:-height,near:1,far:3000});light.shadow.normalBias=.3;scene.add(light);
 const board=new THREE.MeshStandardMaterial({roughness:1,color:0x344559}),paper=new THREE.MeshStandardMaterial({color:0xe8dcc6,roughness:1});bodyResources.push(board,paper);
 function box(w,h,d,x,y,z,material){const geometry=new THREE.BoxGeometry(w,h,d);bodyResources.push(geometry);const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);scene.add(mesh);return mesh;}
 box(width+12,height+12,4,0,-6,-16,board);
 const cover=book.classList.contains('cover-mode');if(cover){box(width-4,height-4,6,2,-3,-7,paper);}else{for(const side of [-1,1])for(let j=0;j<3;j++)box(width/2-2,height-2,1.5,side*width/4,-j*1.6,-j*2-2,paper);}
 const floorGeometry=new THREE.PlaneGeometry(width+pad*2,height+pad*2),floorMaterial=new THREE.ShadowMaterial({opacity:.12});bodyResources.push(floorGeometry,floorMaterial);const floor=new THREE.Mesh(floorGeometry,floorMaterial);floor.position.z=-25;floor.receiveShadow=true;scene.add(floor);bodyRenderer.render(scene,camera);}
new ResizeObserver(drawBody).observe(book);new MutationObserver(drawBody).observe(document.querySelector('#position'),{childList:true,subtree:true,characterData:true});drawBody();

// Warm the two neighbouring leaves so a drag uses the same print texture as button navigation.
window.addEventListener('felt-scene',event=>{const i=event.detail.index;if(i===0||i===event.detail.count-1)return;requestAnimationFrame(()=>{for(const direction of [-1,1]){const target=i+direction;if(target<=0||target>=event.detail.count-1)continue;prepare({host:book,front:window.page(i,direction===1?'right':'left'),back:window.page(target,direction===1?'left':'right')}).catch(()=>{});}});});
