// Private kinetic study: pointer velocity, gravity, air resistance and bounded deposits.
(()=>{
 const canvas=document.querySelector('.wand-dust'),ctx=canvas.getContext('2d');if(!ctx)return;
 const button=document.querySelector('#wand-magic'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
 const preferenceKey='feltworld-landing-effects';
 let preferred=true;try{preferred=localStorage.getItem(preferenceKey)!=='off'}catch{}
 let on=preferred,w=0,h=0,raf=0,last=0,prev=null,particles=[],surfaces=[],dirty=true,serial=0,budget=0,budgetAt=0,nextPacket=0;
 document.querySelectorAll('.card').forEach(card=>{card.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')card.classList.add('touch-pressed')},{passive:true});for(const event of ['pointerup','pointercancel','pointerleave'])card.addEventListener(event,()=>card.classList.remove('touch-pressed'),{passive:true})});addEventListener('blur',()=>document.querySelectorAll('.touch-pressed').forEach(el=>el.classList.remove('touch-pressed')));
 const cap=()=>w<600?500:1000;
 function measure(){surfaces=[...document.querySelectorAll('.card,.landing-divider,.bottom-divider')].map(el=>{const r=el.getBoundingClientRect();return{el,left:r.left+.5,right:r.right-.5,top:r.top+(el.matches('.landing-divider')?4.5:el.matches('.bottom-divider')?1.5:0)}}).filter(r=>r.top>=0&&r.top<h);dirty=false}
 function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);dirty=true;particles=[]}
 function emit(x,y,vx,vy,count){if(!on||reduced.matches||document.hidden)return;for(let n=0;n<count;n++){if(particles.length>=cap())break;particles.push({x:x+(Math.random()+Math.random()-1)*36,y:y+(Math.random()+Math.random()-1)*28,vx:vx*.09+(Math.random()-.5)*140,vy:vy*.07-10-Math.random()*65,size:.6+Math.random()*1.1,age:0,life:7+Math.random()*5,phase:Math.random()*6.28,gravity:12+Math.random()*26,dragX:.35+Math.random()*.85,dragY:.35+Math.random()*.55,rest:null,gold:serial++%3!==0})}wake()}
 function move(e){const t=performance.now(),p=prev;prev={x:e.clientX,y:e.clientY,t};if(!budgetAt)budgetAt=t;if(!p||t-p.t>180){budget=0;budgetAt=t;nextPacket=t;return;}const dt=Math.max(12,t-p.t)/1000,dx=e.clientX-p.x,dy=e.clientY-p.y,speed=Math.min(900,Math.hypot(dx,dy)/dt);if(speed<12)return;budget=Math.min(14,budget+(t-budgetAt)/1000*(w<600?70:100));budgetAt=t;if(t<nextPacket||budget<2)return;const count=Math.min(7,Math.floor(budget));budget-=count;nextPacket=t+25+Math.random()*50;const f=.35+Math.random()*.65;emit(p.x+dx*f,p.y+dy*f,Math.max(-700,Math.min(700,dx/dt)),Math.max(-700,Math.min(700,dy/dt)),count)}
 addEventListener('pointermove',move,{passive:true});addEventListener('pointerdown',e=>{prev={x:e.clientX,y:e.clientY,t:performance.now()};emit(e.clientX,e.clientY,0,0,10)},{passive:true});addEventListener('pointerup',e=>{if(e.pointerType==='touch')prev=null},{passive:true});addEventListener('pointercancel',()=>prev=null);document.addEventListener('pointerleave',()=>prev=null);
 function draw(t){raf=0;const dt=Math.min(.035,last?(t-last)/1000:.016);last=t;measure();ctx.clearRect(0,0,w,h);if(!on||reduced.matches||document.hidden)return;
 particles=particles.filter(p=>p.age<p.life&&p.y<h+20);
 for(const p of particles){p.age+=dt;if(p.rest){const r=surfaces.find(s=>s.el===p.rest.el);if(r){p.x=r.left+p.rest.offset;p.y=r.top-p.size*.3;if(p.x<r.left||p.x>r.right)p.rest=null}else p.rest=null}
 else{const before=p.y;p.vx+=(Math.sin(t*.00025+p.phase*.15)*4)*dt;p.vx*=Math.exp(-dt*p.dragX);p.vy+=p.gravity*dt;p.vy*=Math.exp(-dt*p.dragY);p.x+=p.vx*dt;p.y+=p.vy*dt;
 if(p.vy>0)for(const s of surfaces)if(before<s.top&&p.y>=s.top&&p.x>=s.left&&p.x<=s.right){p.y=s.top-p.size*.3;if(p.vy>22&&!p.bounced){p.vy*=-.18;p.vx*=.45;p.bounced=true}else{p.rest={el:s.el,offset:p.x-s.left};p.vx=p.vy=0;p.life=Math.min(p.life,p.age+2.5+Math.random()*3)}break}}
 const fade=Math.min(1,p.age/.1)*Math.min(1,(p.life-p.age)/2.5),twinkle=.65+.35*Math.sin(t*.003+p.phase)**8;ctx.globalAlpha=fade*(p.rest?.38:twinkle*.75);ctx.fillStyle=p.gold?'#e9c886':'#e9edf1';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();if(!p.rest&&p.size>1.45){ctx.globalAlpha=fade*.22;ctx.strokeStyle=p.gold?'#ffe4aa':'#fff';ctx.lineWidth=.55;ctx.beginPath();ctx.moveTo(p.x-2.5,p.y);ctx.lineTo(p.x+2.5,p.y);ctx.moveTo(p.x,p.y-2.5);ctx.lineTo(p.x,p.y+2.5);ctx.stroke()}}
 canvas.dataset.population=particles.length;canvas.dataset.settled=particles.filter(p=>p.rest).length;canvas.dataset.emitted=serial;if(particles.length)raf=requestAnimationFrame(draw);
 }
 function wake(){if(!raf){last=0;raf=requestAnimationFrame(draw)}}
 function sync(){cancelAnimationFrame(raf);raf=0;particles=[];ctx.clearRect(0,0,w,h);const enabled=on&&!reduced.matches;button.disabled=reduced.matches;button.setAttribute('aria-pressed',String(enabled));document.querySelector('#effects-note').textContent=reduced.matches?'Off — reduced motion':'Turn decorative glitter on or off.';prev=null;budget=0;budgetAt=0;nextPacket=0}
 button.addEventListener('click',()=>{on=!on;try{localStorage.setItem(preferenceKey,on?'on':'off')}catch{}sync()});reduced.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);addEventListener('resize',resize);addEventListener('scroll',()=>{dirty=true},{passive:true});new ResizeObserver(()=>dirty=true).observe(document.querySelector('main'));resize();sync();
})();
